// https://developer.android.com/develop/ui/compose/performance/stability/fix#configuration-file

kotlin.time.Instant
kotlinx.datetime.DatePeriod
kotlinx.datetime.DateTimePeriod
kotlinx.datetime.LocalDate
kotlinx.datetime.LocalDateTime
kotlinx.datetime.LocalTime
kotlinx.datetime.TimeZone
kotlinx.datetime.UtcOffset
